repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
      additional_dependencies: [toml]
      exclude: migrations/, donotuse/
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: ['--in-place', '--pre-summary-newline', '--make-summary-multi-line']
        exclude: migrations/, donotuse/
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3.8
      exclude: migrations/, donotuse/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--config=.flake8', '--max-line-length=90']
        language_version: python3.8
        exclude: migrations/, donotuse/
